//
//  RemoteButtonData.h
//  xbmcremote
//
//  Created by David Fumberger on 5/11/08.
//  Copyright 2008 collect3. All rights reserved.
//

#import <UIKit/UIKit.h>
#define REMOTE_BUTTON_PLAY   0
#define REMOTE_BUTTON_PAUSE  1
#define REMOTE_BUTTON_OK     2
#define REMOTE_BUTTON_NEXT   3
#define REMOTE_BUTTON_PREV   4
#define REMOTE_BUTTON_LEFT   5
#define REMOTE_BUTTON_RIGHT  6
#define REMOTE_BUTTON_UP     7
#define REMOTE_BUTTON_DOWN   8
#define REMOTE_BUTTON_BACK   9
#define REMOTE_BUTTON_UP_DIR 10
#define REMOTE_BUTTON_GUI    11
#define REMOTE_BUTTON_STOP   12
#define REMOTE_BUTTON_FF     13
#define REMOTE_BUTTON_RR	 14
#define REMOTE_BUTTON_SHOW_INFO 15
#define REMOTE_BUTTON_ASPECT_RATIO 16
#define REMOTE_BUTTON_STEP_FORWARD 17
#define REMOTE_BUTTON_STEP_BACK 18
#define REMOTE_BUTTON_SHOW_OSD 19
#define REMOTE_BUTTON_SHOW_SUBTITLES 20
#define REMOTE_BUTTON_NEXT_SUBTITLE 21
#define REMOTE_BUTTON_SHOW_CODEC 22
#define REMOTE_BUTTON_NEXT_PICTURE 23
#define REMOTE_BUTTON_PREV_PICTURE 24
#define REMOTE_BUTTON_ZOOM_OUT 25
#define REMOTE_BUTTON_ZOOM_IN  26
#define REMOTE_BUTTON_ZOOM_NORMAL 27
#define REMOTE_BUTTON_QUEUE_ITEM 28
#define REMOTE_BUTTON_SHOW_PLAYLIST 29
#define REMOTE_BUTTON_ROTATE_PICTURE 30
#define REMOTE_BUTTON_BIG_STEP_FORWARD 31
#define REMOTE_BUTTON_BIG_STEP_BACK 32
#define REMOTE_BUTTON_SHUTDOWN 33
#define REMOTE_BUTTON_RESTART 34
#define REMOTE_BUTTON_CONTEXT_MENU 35
#define REMOTE_BUTTON_NEXT_VIS 36
#define REMOTE_BUTTON_PREV_VIS 37
#define REMOTE_BUTTON_MUTE 38
#define REMOTE_BUTTON_VOLUME_UP 39
#define REMOTE_BUTTON_VOLUME_DOWN 40
#define REMOTE_BUTTON_SCREENSHOT 41
#define REMOTE_BUTTON_CHANGE_RESOLUTION 42
#define REMOTE_BUTTON_UPDATE_MUSIC_LIBRARY 43
#define REMOTE_BUTTON_UPDATE_VIDEO_LIBRARY 44
#define REMOTE_BUTTON_CHANGE_THEME 45
#define REMOTE_BUTTON_EJECT 46
#define REMOTE_BUTTON_PLAY_DVD 47
#define REMOTE_BUTTON_PARTY_MODE_VIDEO 48
#define REMOTE_BUTTON_PARTY_MODE_MUSIC 49
#define REMOTE_BUTTON_PLAY_SPEED_ONE 50
@interface RemoteButtonData : NSObject {
	NSInteger type;
	CGRect    frame;
}
@property (nonatomic, assign) NSInteger type;
@property (nonatomic, assign) CGRect    frame;
- (id)initWithType:(NSInteger)_buttonType;
- (id)initWithType:(NSInteger)_buttonType point:(CGPoint)_point;
@end
